openapi: "3.0.3"
info:
  title: "some title 21Nov 1332"
  contact:
    name: Sample orders Contact data
    url: 'https://developer.mazinger.com'
    email: developer@mazinger.com
  version: v0.0.1
servers:
  - url: 'https://localhost:3000'
paths:
  /foo:
    $ref: foo-path.yml
components:
  schemas:
    Foo:
      $ref: Foo.yml
    Foo2:
      $ref: Foo2.yml
    Bar:
      $ref: Bar.yml
